#!/usr/bin/env ruby
#
# git-autocommit
# Copyright © 2011 Chris Riddoch
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

require 'inotify'
require 'find'
require 'fileutils'

include FileUtils

i = Inotify.new

work_tree = ARGV[0]

t = Thread.new do
  i.each_event do |ev|
    puts "Event: " + ev.name
    puts "Mask: " + ev.mask.to_s
    file = ev.name
    cd(work_tree) do
      `git add .`
      `git commit -m "Autocommit"`
    end
  end
end

Find.find(work_tree) do |e|
  if ['.git'].include?(File.basename(e)) or !File.directory?(e)
    Find.prune
  else
    begin
      puts "Watching #{e}"
      i.add_watch(e, Inotify::CLOSE_WRITE)
    rescue
      puts "Skipping event #{e}: #{$!}"
    end
  end
end

t.join
